name: Windmill 2-Way Sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up jq
        run: sudo apt-get install -y jq
      - name: Windmill 2-way sync
        env:
          WINDMILL_TOKEN: ${{ secrets.WINDMILL_TOKEN }}
        run: bash windmill-sync/sync.sh
      - name: Push changes
        run: |
          git push || echo "No changes to push"
